#!/usr/bin/env python3

"""
Hey is an AI Personality Chatbot for Task Execution

A simple program for running a chatbot that can execute tasks.
"""

from __future__ import annotations
import os
import argparse
import logging
import requests

logger = logging.getLogger(__name__)
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)

API = os.getenv("HEY_API", "http://localhost:23450")
USER = os.getenv("HEY_USER") or os.getenv("USER", "User")


def send_message(message: str):
    """Call the HeyGPT API to send a message to the chatbot."""
    try:
        # Pull the username from the environment
        reply = requests.post(f"{API}/chat/message", json={"sender_name": USER, "message": message}).json()
        print(f"{reply['message']}")
    except KeyboardInterrupt:
        print("\nGoodbye!")


def main(message: str):
    """Call the HeyGPT API to send a message to the chatbot."""
    # If no message is provided, then we are in interactive mode.
    while not message:
        try:
            if message:
                send_message(message)
            else:
                message = input("You: ")
                send_message(message)
        except KeyboardInterrupt:
            print("\nGoodbye!")
            break
        except Exception as e:
            logger.error(e)
            break
        finally:
            message = None
    else:
        # If a message is provided, then we are in single message mode.
        # Send the message to the chatbot and print the response.
        send_message(message)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Hey is an AI Personality Chatbot")
    parser.add_argument("message", type=str, help="the message to send to the chatbot")
    args = parser.parse_args()
    main(args.message)
